fix(_create_session): remove broken debug print
291b4cefcf957ba5b48569d891e19c05940d9e33 add a debug print
that only works if user/password is used.

```

File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py",
line 3226, in _create_session
LOGGER.debug("Session authorization provider: user '%s',
password '%s'", cluster_driver.auth_provider.username,
AttributeError: 'NoneType' object has no attribute 'username'
```